website/config/routes.rb
Rails.application.routes.draw do


  devise_for :students


  namespace :api, defaults: { format: :json } do
      resources :records do
        collection do
          post 'get_records_by_email'
          post 'save_record'
          get 'get_level'
          post 'user_login'
        end
      end
  end

  
  root 'home#index'
end

website/app/models/record.rb
class Record < ActiveRecord::Base
end

website/app/models/student.rb
class Student < ActiveRecord::Base

	 EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
	 validates :email,
  		:presence => true,
  		:uniqueness => {
    	:case_sensitive => false
    }


    	
 def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_h).first
      end
    end



def self.authenticate(username_or_email="", login_password="")
  if  EMAIL_REGEX.match(username_or_email)    
    user = Student.find_by_email(username_or_email)
  end
  if user && user.match_password(login_password)
    return user
  else
    return false
  end
end   



def match_password(login_password="")
  encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
end



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

website/app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController



    respond_to :json
    skip_before_action :verify_authenticity_token
    

    
end

website/app/controllers/api/records_controller.rb
class Api::RecordsController < Api::BaseController



	def user_login
		@email = params[:email]
		@password = params[:password]
		@user = Student.find_by_email(params[:email])
		if @user
			if @user.valid_password?(params[:password])
				render status: 200
			else
				render status: 401
			end
		else
			render status: 401
		end
	end
		


	def get_records_by_email
		#get the email that identifies the user
		@email = params[:email]
		#logic goes here to get @records
		@records = Record.where(email: @email).order(created_at: :desc) ### code here
		respond_with @records
	end


	
	def save_record
		#get the parameters fom the post params
		@time = params[:time]
		@score = params[:score]
		@level = params[:level]
		@clicks = params[:clicks]
		@email = params[:email]
		#create new record
		@record = Record.new(time: @time, score: @score, level: @level, clicks: @clicks, email: @email)
		#if the recordsis save , respond with OK , else rrespond with  error status(errors in parametrs)
		if @record.save 
			render status: 201
		else
			render status: 422
		end

	end


  
    def get_level
	  	@email = params[:email]
	  	@records = Record.where(email: @email)
	  	@record=@records.last
	end



end

website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :configure_permited_params , if: :devise_controller?
	  include SessionsHelper
	def configure_permited_params
		devise_parameter_sanitizer.for(:sign_up) << [:school , :grade , :student_name , :student_class]
	end


	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

website/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		unless current_student
			redirect_to new_student_session_path
		end
	end


end

website/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end



  def create
    user = Student.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to("home#index")
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end



  def destroy
  end
end

website/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def show
    @user = Student.find(params[:id])
  end



  def new
    @user = Student.new
  end



  def create
    @user = Student.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome!"
      redirect_to("home#index")
    else
      render 'new'
    end
  end



  private
    def user_params
      params.require(:student).permit(:email, :password,
                                   :password_confirmation)
    end
end

website/app/helpers/application_helper.rb
module ApplicationHelper
end

website/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end



    # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= Student.find_by(id: session[:user_id])
  end



   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

website/app/helpers/students_controller_helper.rb
module StudentsControllerHelper
end

website/app/views/home/index.html.erb
<div class="row">
  <br>
  <br>
  <br>
</div>
<div class="row">
  <div class="col-md-2">
    <div class="list-group" width="70px;">
      <a href="#" class="list-group-item">First item</a>
      <a href="#" class="list-group-item">Second item</a>
      <a href="#" class="list-group-item">Third item</a>
      <a href="#" class="list-group-item">Fourth item</a>
      <a href="#" class="list-group-item">Fifth item</a>
    </div>
  </div>
  <div class="col-md-8">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="/LightG.html" width="800px;" height="700px;"></iframe>
    </div>
  </div>
</div>

website/app/views/layouts/_flash_messages.html.erb
<p>
	<% if flash.present? %>
		<% flash.each do |type, message| %>
				<% @type2 = type.titleize %>
				<% if @type2 == "notice" %>
					<div class="alert alert-success"> 
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
     				 		&times;
   						</button>
						<%= message %>
					</div>
				<% else %>
					<div class="alert alert-warning">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
     						 &times;
   						</button>
						<%= message %>
					</div>
				<% end %>
		<% end %>
	<% end %>
</p>

website/app/views/layouts/_headers.html.erb
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <a class="navbar-brand" href="#">K-12</a>
   </div>
   <div>
   <% if current_student %>
   	<p class="navbar-text navbar-right">  <%= link_to "Sign out", destroy_student_session_path, :method => :delete %>
      </p>
      <p class="navbar-text navbar-right"><b>Signed in as <%= current_student.email %></b> </p>
    <% end %>   
   </div>
</div>

website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
      <%= render partial: 'layouts/flash_messages' %>
      <%= render partial: 'layouts/headers' %>
      <div>
          <%= yield %>
      </div>
  </div>

</body>
</html>